# stores HSV color thresholds for {blue, green, red, yellow}
RedHSV: {low: [114, 147, 175], high: [179, 247, 255]}
BlueHSV: {low: [110, 100, 100], high: [130, 255, 255]}
GreenHSV: {low: [71, 133, 154], high: [121, 183, 204]}
YellowHSV: {low: [5, 0, 206], high: [55, 35, 255]}
BoxHSV: {low: [117, 114, 87], high: [179, 214, 187]}

FindBlue: True
FindGreen: False
FindRed: True
FindYellow: True
